### ISSUE TITLE
get_events(b, limit = None) returns only 100 events.

### ISSUE THREAD

**Issue by nikanar** [ActivityWatch/aw-client#23]
```
import aw_client
ac = aw_client.ActivityWatchClient("_")
ac.connect()
afk_events = ac.get_events("aw-watcher-afk_ker")
print(len(afk_events))
# returns 100, same as 8h ago.
```

I think these 100 are the latest events, but I would like to get them all.
I would expect `limit=None` (the current default value) to not put a limit, and return them all.

I *can* get them all with `limit = 10**6` because apparently I have 430 of them total.

**Comment by johan-bjareholt** [comment]
If i remember correctly our reason for setting the limit to 100 was so activitywatch wouldn't take up all CPU and disk usage by dumping the whole bucket if someone had run activitywatch for a long period of time. Now when i think of it it's kind of stupid, but still valid I guess. At least we should document it somewhere.

@ErikBjare Should we remove the default 100 event limit or keep it?

Instead of setting `limit = 10**6` you can use `limit = -1` to fetch all events.

By the way @nikanar, if you havn't seen it yet you can have a nice view of the REST api at localhost:5600/api, could be useful.

**Comment by ErikBjare** [comment]
The default limit is 100 by default for very reason that Johan explained. 

That being said, it might be better to have 100 as the default argument in ´aw-client´ and make ´limit=None´ mean that ´limit=-1´ is passed to the API.

And again @nikanar, I can't thank you enough for the work you are doing here ❤️

**Comment by johan-bjareholt** [comment]
Fixed

aw-client: https://github.com/ActivityWatch/aw-client/commit/4b11b943f0064f3e9a38288a18a2a9e6c96eedd5

aw-server: https://github.com/ActivityWatch/aw-server/commit/3d841d9d490b05c4df8db7ccb0b490ad07f0c699
